### ISSUE TITLE
Game won't load with mod

### ISSUE THREAD

**Issue by McWendigoes** [MystDevMC/recicropal#1]
Game won't load, something to do with registrate.

[latest.log](https://github.com/MystDevMC/recicropal/files/12049718/latest.log)

**Comment by MystDevMC** [comment]
Hmm I think I know what's the problem.

Which version of the mod you are using? Also, did you get it from Modrinth or CurseForge?

**Comment by MystDevMC** [comment]
This is caused by a stupid mishap where I forgot to enable Forge's `jarJar` option so the distributed mod doesn't come with Registrate. This would be an issue if you don't run the mod along with other mods that have it as a dependency such as `create`.

I hope the latest file on [Modrinth](https://modrinth.com/mod/recicropal) would solve your problem. Thanks for reporting this. 

Tested it locally with no other mods containing Registrate and it ran. Reopen this if it still fails.

**Comment by McWendigoes** [comment]
Thanks, loaded in correctly. Not really relevant considering it works now, but got off modrinth.
